/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgRouteRouteImport } from './routes/_authenticated/_org/route'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthenticatedObligationsIndexRouteImport } from './routes/_authenticated/obligations/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthRegisterSplatRouteImport } from './routes/auth/register/$'
import { Route as AuthLoginSplatRouteImport } from './routes/auth/login/$'
import { Route as AuthenticatedObligationsReviewRouteImport } from './routes/_authenticated/obligations/review'
import { Route as AuthenticatedObligationsObligationIdRouteImport } from './routes/_authenticated/obligations/$obligationId'
import { Route as AuthenticatedDocumentsDocumentIdRouteImport } from './routes/_authenticated/documents/$documentId'
import { Route as AuthenticatedOrgOnboardingIndexRouteImport } from './routes/_authenticated/_org/onboarding/index'
import { Route as AuthenticatedOrgGapsIndexRouteImport } from './routes/_authenticated/_org/gaps/index'
import { Route as AuthenticatedOrgDashboardIndexRouteImport } from './routes/_authenticated/_org/dashboard/index'
import { Route as AuthenticatedOrgClientsIndexRouteImport } from './routes/_authenticated/_org/clients/index'
import { Route as AuthenticatedOrgChecklistsIndexRouteImport } from './routes/_authenticated/_org/checklists/index'
import { Route as AuthenticatedOrgSettingsOrganizationRouteImport } from './routes/_authenticated/_org/settings/organization'
import { Route as AuthenticatedOrgGapsGapIdRouteImport } from './routes/_authenticated/_org/gaps/$gapId'
import { Route as AuthenticatedOrgChecklistsChecklistItemIdRouteImport } from './routes/_authenticated/_org/checklists/$checklistItemId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgRouteRoute = AuthenticatedOrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObligationsIndexRoute =
  AuthenticatedObligationsIndexRouteImport.update({
    id: '/obligations/',
    path: '/obligations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthRegisterSplatRoute = AuthRegisterSplatRouteImport.update({
  id: '/auth/register/$',
  path: '/auth/register/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginSplatRoute = AuthLoginSplatRouteImport.update({
  id: '/auth/login/$',
  path: '/auth/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedObligationsReviewRoute =
  AuthenticatedObligationsReviewRouteImport.update({
    id: '/obligations/review',
    path: '/obligations/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedObligationsObligationIdRoute =
  AuthenticatedObligationsObligationIdRouteImport.update({
    id: '/obligations/$obligationId',
    path: '/obligations/$obligationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsDocumentIdRoute =
  AuthenticatedDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgOnboardingIndexRoute =
  AuthenticatedOrgOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgGapsIndexRoute =
  AuthenticatedOrgGapsIndexRouteImport.update({
    id: '/gaps/',
    path: '/gaps/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgDashboardIndexRoute =
  AuthenticatedOrgDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgClientsIndexRoute =
  AuthenticatedOrgClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgChecklistsIndexRoute =
  AuthenticatedOrgChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgSettingsOrganizationRoute =
  AuthenticatedOrgSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgGapsGapIdRoute =
  AuthenticatedOrgGapsGapIdRouteImport.update({
    id: '/gaps/$gapId',
    path: '/gaps/$gapId',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgChecklistsChecklistItemIdRoute =
  AuthenticatedOrgChecklistsChecklistItemIdRouteImport.update({
    id: '/checklists/$checklistItemId',
    path: '/checklists/$checklistItemId',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/obligations/$obligationId': typeof AuthenticatedObligationsObligationIdRoute
  '/obligations/review': typeof AuthenticatedObligationsReviewRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/register/$': typeof AuthRegisterSplatRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/obligations/': typeof AuthenticatedObligationsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/checklists/$checklistItemId': typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  '/gaps/$gapId': typeof AuthenticatedOrgGapsGapIdRoute
  '/settings/organization': typeof AuthenticatedOrgSettingsOrganizationRoute
  '/checklists/': typeof AuthenticatedOrgChecklistsIndexRoute
  '/clients/': typeof AuthenticatedOrgClientsIndexRoute
  '/dashboard/': typeof AuthenticatedOrgDashboardIndexRoute
  '/gaps/': typeof AuthenticatedOrgGapsIndexRoute
  '/onboarding/': typeof AuthenticatedOrgOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/obligations/$obligationId': typeof AuthenticatedObligationsObligationIdRoute
  '/obligations/review': typeof AuthenticatedObligationsReviewRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/register/$': typeof AuthRegisterSplatRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/obligations': typeof AuthenticatedObligationsIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/checklists/$checklistItemId': typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  '/gaps/$gapId': typeof AuthenticatedOrgGapsGapIdRoute
  '/settings/organization': typeof AuthenticatedOrgSettingsOrganizationRoute
  '/checklists': typeof AuthenticatedOrgChecklistsIndexRoute
  '/clients': typeof AuthenticatedOrgClientsIndexRoute
  '/dashboard': typeof AuthenticatedOrgDashboardIndexRoute
  '/gaps': typeof AuthenticatedOrgGapsIndexRoute
  '/onboarding': typeof AuthenticatedOrgOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_org': typeof AuthenticatedOrgRouteRouteWithChildren
  '/_authenticated/documents/$documentId': typeof AuthenticatedDocumentsDocumentIdRoute
  '/_authenticated/obligations/$obligationId': typeof AuthenticatedObligationsObligationIdRoute
  '/_authenticated/obligations/review': typeof AuthenticatedObligationsReviewRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/register/$': typeof AuthRegisterSplatRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/obligations/': typeof AuthenticatedObligationsIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_org/checklists/$checklistItemId': typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  '/_authenticated/_org/gaps/$gapId': typeof AuthenticatedOrgGapsGapIdRoute
  '/_authenticated/_org/settings/organization': typeof AuthenticatedOrgSettingsOrganizationRoute
  '/_authenticated/_org/checklists/': typeof AuthenticatedOrgChecklistsIndexRoute
  '/_authenticated/_org/clients/': typeof AuthenticatedOrgClientsIndexRoute
  '/_authenticated/_org/dashboard/': typeof AuthenticatedOrgDashboardIndexRoute
  '/_authenticated/_org/gaps/': typeof AuthenticatedOrgGapsIndexRoute
  '/_authenticated/_org/onboarding/': typeof AuthenticatedOrgOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents/$documentId'
    | '/obligations/$obligationId'
    | '/obligations/review'
    | '/auth/login/$'
    | '/auth/register/$'
    | '/documents/'
    | '/obligations/'
    | '/auth/login/'
    | '/auth/register/'
    | '/checklists/$checklistItemId'
    | '/gaps/$gapId'
    | '/settings/organization'
    | '/checklists/'
    | '/clients/'
    | '/dashboard/'
    | '/gaps/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents/$documentId'
    | '/obligations/$obligationId'
    | '/obligations/review'
    | '/auth/login/$'
    | '/auth/register/$'
    | '/documents'
    | '/obligations'
    | '/auth/login'
    | '/auth/register'
    | '/checklists/$checklistItemId'
    | '/gaps/$gapId'
    | '/settings/organization'
    | '/checklists'
    | '/clients'
    | '/dashboard'
    | '/gaps'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_org'
    | '/_authenticated/documents/$documentId'
    | '/_authenticated/obligations/$obligationId'
    | '/_authenticated/obligations/review'
    | '/auth/login/$'
    | '/auth/register/$'
    | '/_authenticated/documents/'
    | '/_authenticated/obligations/'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_org/checklists/$checklistItemId'
    | '/_authenticated/_org/gaps/$gapId'
    | '/_authenticated/_org/settings/organization'
    | '/_authenticated/_org/checklists/'
    | '/_authenticated/_org/clients/'
    | '/_authenticated/_org/dashboard/'
    | '/_authenticated/_org/gaps/'
    | '/_authenticated/_org/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginSplatRoute: typeof AuthLoginSplatRoute
  AuthRegisterSplatRoute: typeof AuthRegisterSplatRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_org': {
      id: '/_authenticated/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrgRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obligations/': {
      id: '/_authenticated/obligations/'
      path: '/obligations'
      fullPath: '/obligations/'
      preLoaderRoute: typeof AuthenticatedObligationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/register/$': {
      id: '/auth/register/$'
      path: '/auth/register/$'
      fullPath: '/auth/register/$'
      preLoaderRoute: typeof AuthRegisterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/$': {
      id: '/auth/login/$'
      path: '/auth/login/$'
      fullPath: '/auth/login/$'
      preLoaderRoute: typeof AuthLoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/obligations/review': {
      id: '/_authenticated/obligations/review'
      path: '/obligations/review'
      fullPath: '/obligations/review'
      preLoaderRoute: typeof AuthenticatedObligationsReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obligations/$obligationId': {
      id: '/_authenticated/obligations/$obligationId'
      path: '/obligations/$obligationId'
      fullPath: '/obligations/$obligationId'
      preLoaderRoute: typeof AuthenticatedObligationsObligationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/$documentId': {
      id: '/_authenticated/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_org/onboarding/': {
      id: '/_authenticated/_org/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOrgOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/gaps/': {
      id: '/_authenticated/_org/gaps/'
      path: '/gaps'
      fullPath: '/gaps/'
      preLoaderRoute: typeof AuthenticatedOrgGapsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/dashboard/': {
      id: '/_authenticated/_org/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedOrgDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/clients/': {
      id: '/_authenticated/_org/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedOrgClientsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/checklists/': {
      id: '/_authenticated/_org/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedOrgChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/settings/organization': {
      id: '/_authenticated/_org/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedOrgSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/gaps/$gapId': {
      id: '/_authenticated/_org/gaps/$gapId'
      path: '/gaps/$gapId'
      fullPath: '/gaps/$gapId'
      preLoaderRoute: typeof AuthenticatedOrgGapsGapIdRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/checklists/$checklistItemId': {
      id: '/_authenticated/_org/checklists/$checklistItemId'
      path: '/checklists/$checklistItemId'
      fullPath: '/checklists/$checklistItemId'
      preLoaderRoute: typeof AuthenticatedOrgChecklistsChecklistItemIdRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
  }
}

interface AuthenticatedOrgRouteRouteChildren {
  AuthenticatedOrgChecklistsChecklistItemIdRoute: typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  AuthenticatedOrgGapsGapIdRoute: typeof AuthenticatedOrgGapsGapIdRoute
  AuthenticatedOrgSettingsOrganizationRoute: typeof AuthenticatedOrgSettingsOrganizationRoute
  AuthenticatedOrgChecklistsIndexRoute: typeof AuthenticatedOrgChecklistsIndexRoute
  AuthenticatedOrgClientsIndexRoute: typeof AuthenticatedOrgClientsIndexRoute
  AuthenticatedOrgDashboardIndexRoute: typeof AuthenticatedOrgDashboardIndexRoute
  AuthenticatedOrgGapsIndexRoute: typeof AuthenticatedOrgGapsIndexRoute
  AuthenticatedOrgOnboardingIndexRoute: typeof AuthenticatedOrgOnboardingIndexRoute
}

const AuthenticatedOrgRouteRouteChildren: AuthenticatedOrgRouteRouteChildren = {
  AuthenticatedOrgChecklistsChecklistItemIdRoute:
    AuthenticatedOrgChecklistsChecklistItemIdRoute,
  AuthenticatedOrgGapsGapIdRoute: AuthenticatedOrgGapsGapIdRoute,
  AuthenticatedOrgSettingsOrganizationRoute:
    AuthenticatedOrgSettingsOrganizationRoute,
  AuthenticatedOrgChecklistsIndexRoute: AuthenticatedOrgChecklistsIndexRoute,
  AuthenticatedOrgClientsIndexRoute: AuthenticatedOrgClientsIndexRoute,
  AuthenticatedOrgDashboardIndexRoute: AuthenticatedOrgDashboardIndexRoute,
  AuthenticatedOrgGapsIndexRoute: AuthenticatedOrgGapsIndexRoute,
  AuthenticatedOrgOnboardingIndexRoute: AuthenticatedOrgOnboardingIndexRoute,
}

const AuthenticatedOrgRouteRouteWithChildren =
  AuthenticatedOrgRouteRoute._addFileChildren(
    AuthenticatedOrgRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgRouteRoute: typeof AuthenticatedOrgRouteRouteWithChildren
  AuthenticatedDocumentsDocumentIdRoute: typeof AuthenticatedDocumentsDocumentIdRoute
  AuthenticatedObligationsObligationIdRoute: typeof AuthenticatedObligationsObligationIdRoute
  AuthenticatedObligationsReviewRoute: typeof AuthenticatedObligationsReviewRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedObligationsIndexRoute: typeof AuthenticatedObligationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgRouteRoute: AuthenticatedOrgRouteRouteWithChildren,
  AuthenticatedDocumentsDocumentIdRoute: AuthenticatedDocumentsDocumentIdRoute,
  AuthenticatedObligationsObligationIdRoute:
    AuthenticatedObligationsObligationIdRoute,
  AuthenticatedObligationsReviewRoute: AuthenticatedObligationsReviewRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedObligationsIndexRoute: AuthenticatedObligationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginSplatRoute: AuthLoginSplatRoute,
  AuthRegisterSplatRoute: AuthRegisterSplatRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
