/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgRouteRouteImport } from './routes/_authenticated/_org/route'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthRegisterSplatRouteImport } from './routes/auth/register/$'
import { Route as AuthLoginSplatRouteImport } from './routes/auth/login/$'
import { Route as AuthenticatedOrgOnboardingIndexRouteImport } from './routes/_authenticated/_org/onboarding/index'
import { Route as AuthenticatedOrgDashboardIndexRouteImport } from './routes/_authenticated/_org/dashboard/index'
import { Route as AuthenticatedOrgChecklistsIndexRouteImport } from './routes/_authenticated/_org/checklists/index'
import { Route as AuthenticatedOrgChecklistsChecklistItemIdRouteImport } from './routes/_authenticated/_org/checklists/$checklistItemId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgRouteRoute = AuthenticatedOrgRouteRouteImport.update({
  id: '/_org',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterSplatRoute = AuthRegisterSplatRouteImport.update({
  id: '/auth/register/$',
  path: '/auth/register/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginSplatRoute = AuthLoginSplatRouteImport.update({
  id: '/auth/login/$',
  path: '/auth/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgOnboardingIndexRoute =
  AuthenticatedOrgOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgDashboardIndexRoute =
  AuthenticatedOrgDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgChecklistsIndexRoute =
  AuthenticatedOrgChecklistsIndexRouteImport.update({
    id: '/checklists/',
    path: '/checklists/',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)
const AuthenticatedOrgChecklistsChecklistItemIdRoute =
  AuthenticatedOrgChecklistsChecklistItemIdRouteImport.update({
    id: '/checklists/$checklistItemId',
    path: '/checklists/$checklistItemId',
    getParentRoute: () => AuthenticatedOrgRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/register/$': typeof AuthRegisterSplatRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/checklists/$checklistItemId': typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  '/checklists/': typeof AuthenticatedOrgChecklistsIndexRoute
  '/dashboard/': typeof AuthenticatedOrgDashboardIndexRoute
  '/onboarding/': typeof AuthenticatedOrgOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/register/$': typeof AuthRegisterSplatRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/checklists/$checklistItemId': typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  '/checklists': typeof AuthenticatedOrgChecklistsIndexRoute
  '/dashboard': typeof AuthenticatedOrgDashboardIndexRoute
  '/onboarding': typeof AuthenticatedOrgOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/_org': typeof AuthenticatedOrgRouteRouteWithChildren
  '/auth/login/$': typeof AuthLoginSplatRoute
  '/auth/register/$': typeof AuthRegisterSplatRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/_authenticated/_org/checklists/$checklistItemId': typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  '/_authenticated/_org/checklists/': typeof AuthenticatedOrgChecklistsIndexRoute
  '/_authenticated/_org/dashboard/': typeof AuthenticatedOrgDashboardIndexRoute
  '/_authenticated/_org/onboarding/': typeof AuthenticatedOrgOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login/$'
    | '/auth/register/$'
    | '/auth/login/'
    | '/auth/register/'
    | '/checklists/$checklistItemId'
    | '/checklists/'
    | '/dashboard/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login/$'
    | '/auth/register/$'
    | '/auth/login'
    | '/auth/register'
    | '/checklists/$checklistItemId'
    | '/checklists'
    | '/dashboard'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_org'
    | '/auth/login/$'
    | '/auth/register/$'
    | '/auth/login/'
    | '/auth/register/'
    | '/_authenticated/_org/checklists/$checklistItemId'
    | '/_authenticated/_org/checklists/'
    | '/_authenticated/_org/dashboard/'
    | '/_authenticated/_org/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthLoginSplatRoute: typeof AuthLoginSplatRoute
  AuthRegisterSplatRoute: typeof AuthRegisterSplatRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_org': {
      id: '/_authenticated/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedOrgRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/$': {
      id: '/auth/register/$'
      path: '/auth/register/$'
      fullPath: '/auth/register/$'
      preLoaderRoute: typeof AuthRegisterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/$': {
      id: '/auth/login/$'
      path: '/auth/login/$'
      fullPath: '/auth/login/$'
      preLoaderRoute: typeof AuthLoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_org/onboarding/': {
      id: '/_authenticated/_org/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOrgOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/dashboard/': {
      id: '/_authenticated/_org/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedOrgDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/checklists/': {
      id: '/_authenticated/_org/checklists/'
      path: '/checklists'
      fullPath: '/checklists/'
      preLoaderRoute: typeof AuthenticatedOrgChecklistsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
    '/_authenticated/_org/checklists/$checklistItemId': {
      id: '/_authenticated/_org/checklists/$checklistItemId'
      path: '/checklists/$checklistItemId'
      fullPath: '/checklists/$checklistItemId'
      preLoaderRoute: typeof AuthenticatedOrgChecklistsChecklistItemIdRouteImport
      parentRoute: typeof AuthenticatedOrgRouteRoute
    }
  }
}

interface AuthenticatedOrgRouteRouteChildren {
  AuthenticatedOrgChecklistsChecklistItemIdRoute: typeof AuthenticatedOrgChecklistsChecklistItemIdRoute
  AuthenticatedOrgChecklistsIndexRoute: typeof AuthenticatedOrgChecklistsIndexRoute
  AuthenticatedOrgDashboardIndexRoute: typeof AuthenticatedOrgDashboardIndexRoute
  AuthenticatedOrgOnboardingIndexRoute: typeof AuthenticatedOrgOnboardingIndexRoute
}

const AuthenticatedOrgRouteRouteChildren: AuthenticatedOrgRouteRouteChildren = {
  AuthenticatedOrgChecklistsChecklistItemIdRoute:
    AuthenticatedOrgChecklistsChecklistItemIdRoute,
  AuthenticatedOrgChecklistsIndexRoute: AuthenticatedOrgChecklistsIndexRoute,
  AuthenticatedOrgDashboardIndexRoute: AuthenticatedOrgDashboardIndexRoute,
  AuthenticatedOrgOnboardingIndexRoute: AuthenticatedOrgOnboardingIndexRoute,
}

const AuthenticatedOrgRouteRouteWithChildren =
  AuthenticatedOrgRouteRoute._addFileChildren(
    AuthenticatedOrgRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrgRouteRoute: typeof AuthenticatedOrgRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrgRouteRoute: AuthenticatedOrgRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthLoginSplatRoute: AuthLoginSplatRoute,
  AuthRegisterSplatRoute: AuthRegisterSplatRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
